Algoritmo "Exercício_2"
// Disciplina  : Algoritmo
// Professor   : Leandro Gonzalez
// Descrição   : Informa se a senha é válida ou inválida (Senha: PORTUGOL)
// Autor(a)    : Leandro Lima

Var
   senha : caractere

Inicio
   escreva("Digite a senha: ")
   leia(senha)
   
   se senha = "PORTUGOL" entao
      escreval("Senha Válida!")
   senao
      escreval("Senha Inválida!")
   fimse


Fimalgoritmo