Algoritmo "Exercício_5"
// Disciplina  : Algoritmo
// Professor   : Leandro Gonzalez
// Descrição   : Informa se o número é divisível por 5
// Autor(a)    : Leandro Lima

Var
   N : inteiro

Inicio
   escreva("Digite um número inteiro: ")
   leia(N)
   
   se N MOD 5 = 0 entao
      escreva("O número é divisível por 5.")
   senao
      escreva("O número NÃO é divisível por 5.")
   fimse

Fimalgoritmo