Algoritmo "Exercício_1"
// Disciplina  : Algoritmo
// Professor   : Leandro Gonzalez
// Descrição   : Informa quando o número escolhido é maior que 100
// Autor(a)    : Leandro Lima

Var
   N : real

Inicio
   escreva("Escolha um número: ")
   leia(N)
   
   se N > 100 entao
      escreval("O número escolhido é maior que 100.")
   senao
      escreval("O número escolhido é menor que 100.")
   fimse


Fimalgoritmo